### ISSUE TITLE
Sanitinize modules input names.

### ISSUE THREAD

**Issue by jfigueruela** [natete/generator-reqionic#7]
- Set user's input modules names to lowercase and remove special chars.
  e.g.  Module -> module
         My Module -> mymodule

**Comment by jfigueruela** [comment]
see https://lodash.com/

**Comment by agomezmoron** [comment]
Is it this issue finished or do we have to push to the new milestone?

**Comment by jfigueruela** [comment]
Moved into 0.0.4-Threepwood milestone. ;)
